import 'package:get/get.dart';
import 'package:cadastros/app/page/shared_widget/shared_widget_imports.dart';
import 'package:cadastros/app/routes/app_routes.dart';
import 'package:cadastros/app/page/login/login_page.dart';
import 'package:cadastros/app/page/shared_page/splash_screen_page.dart';
import 'package:cadastros/app/bindings/bindings_imports.dart';
import 'package:cadastros/app/page/shared_page/shared_page_imports.dart';
import 'package:cadastros/app/page/page_imports.dart';

class AppPages {
	
	static final pages = [
		GetPage(name: Routes.splashPage, page:()=> const SplashScreenPage()),
		GetPage(name: Routes.loginPage, page:()=> const LoginPage(), binding: LoginBindings()),
		GetPage(name: Routes.homePage, page:()=> HomePage()),
		GetPage(name: Routes.filterPage, page:()=> const FilterPage()),
		GetPage(name: Routes.lookupPage, page:()=> const LookupPage()),
    GetPage(name: Routes.menuModulesPage, page:()=> const MenuModulesPage()),
		
		GetPage(name: Routes.pessoaListPage, page:()=> const PessoaListPage(), binding: PessoaBindings()), 
		GetPage(name: Routes.pessoaTabPage, page:()=> PessoaTabPage()),
		GetPage(name: Routes.colaboradorListPage, page:()=> const ColaboradorListPage(), binding: ColaboradorBindings()), 
		GetPage(name: Routes.colaboradorTabPage, page:()=> ColaboradorTabPage()),
		GetPage(name: Routes.estadoCivilListPage, page:()=> const EstadoCivilListPage(), binding: EstadoCivilBindings()), 
		GetPage(name: Routes.estadoCivilEditPage, page:()=> EstadoCivilEditPage()),
		GetPage(name: Routes.cargoListPage, page:()=> const CargoListPage(), binding: CargoBindings()), 
		GetPage(name: Routes.cargoEditPage, page:()=> CargoEditPage()),
		GetPage(name: Routes.setorListPage, page:()=> const SetorListPage(), binding: SetorBindings()), 
		GetPage(name: Routes.setorEditPage, page:()=> SetorEditPage()),
		GetPage(name: Routes.colaboradorSituacaoListPage, page:()=> const ColaboradorSituacaoListPage(), binding: ColaboradorSituacaoBindings()), 
		GetPage(name: Routes.colaboradorSituacaoEditPage, page:()=> ColaboradorSituacaoEditPage()),
		GetPage(name: Routes.tipoAdmissaoListPage, page:()=> const TipoAdmissaoListPage(), binding: TipoAdmissaoBindings()), 
		GetPage(name: Routes.tipoAdmissaoEditPage, page:()=> TipoAdmissaoEditPage()),
		GetPage(name: Routes.colaboradorTipoListPage, page:()=> const ColaboradorTipoListPage(), binding: ColaboradorTipoBindings()), 
		GetPage(name: Routes.colaboradorTipoEditPage, page:()=> ColaboradorTipoEditPage()),
		GetPage(name: Routes.produtoGrupoListPage, page:()=> const ProdutoGrupoListPage(), binding: ProdutoGrupoBindings()), 
		GetPage(name: Routes.produtoGrupoEditPage, page:()=> ProdutoGrupoEditPage()),
		GetPage(name: Routes.produtoSubgrupoListPage, page:()=> const ProdutoSubgrupoListPage(), binding: ProdutoSubgrupoBindings()), 
		GetPage(name: Routes.produtoSubgrupoEditPage, page:()=> ProdutoSubgrupoEditPage()),
		GetPage(name: Routes.produtoMarcaListPage, page:()=> const ProdutoMarcaListPage(), binding: ProdutoMarcaBindings()), 
		GetPage(name: Routes.produtoMarcaEditPage, page:()=> ProdutoMarcaEditPage()),
		GetPage(name: Routes.produtoUnidadeListPage, page:()=> const ProdutoUnidadeListPage(), binding: ProdutoUnidadeBindings()), 
		GetPage(name: Routes.produtoUnidadeEditPage, page:()=> ProdutoUnidadeEditPage()),
		GetPage(name: Routes.produtoListPage, page:()=> const ProdutoListPage(), binding: ProdutoBindings()), 
		GetPage(name: Routes.produtoEditPage, page:()=> ProdutoEditPage()),
		GetPage(name: Routes.bancoListPage, page:()=> const BancoListPage(), binding: BancoBindings()), 
		GetPage(name: Routes.bancoEditPage, page:()=> BancoEditPage()),
		GetPage(name: Routes.bancoAgenciaListPage, page:()=> const BancoAgenciaListPage(), binding: BancoAgenciaBindings()), 
		GetPage(name: Routes.bancoAgenciaEditPage, page:()=> BancoAgenciaEditPage()),
		GetPage(name: Routes.bancoContaCaixaListPage, page:()=> const BancoContaCaixaListPage(), binding: BancoContaCaixaBindings()), 
		GetPage(name: Routes.bancoContaCaixaEditPage, page:()=> BancoContaCaixaEditPage()),
		GetPage(name: Routes.cepListPage, page:()=> const CepListPage(), binding: CepBindings()), 
		GetPage(name: Routes.cepEditPage, page:()=> CepEditPage()),
		GetPage(name: Routes.ufListPage, page:()=> const UfListPage(), binding: UfBindings()), 
		GetPage(name: Routes.ufEditPage, page:()=> UfEditPage()),
		GetPage(name: Routes.municipioListPage, page:()=> const MunicipioListPage(), binding: MunicipioBindings()), 
		GetPage(name: Routes.municipioEditPage, page:()=> MunicipioEditPage()),
		GetPage(name: Routes.ncmListPage, page:()=> const NcmListPage(), binding: NcmBindings()), 
		GetPage(name: Routes.ncmEditPage, page:()=> NcmEditPage()),
		GetPage(name: Routes.cfopListPage, page:()=> const CfopListPage(), binding: CfopBindings()), 
		GetPage(name: Routes.cfopEditPage, page:()=> CfopEditPage()),
		GetPage(name: Routes.cstIcmsListPage, page:()=> const CstIcmsListPage(), binding: CstIcmsBindings()), 
		GetPage(name: Routes.cstIcmsEditPage, page:()=> CstIcmsEditPage()),
		GetPage(name: Routes.cstIpiListPage, page:()=> const CstIpiListPage(), binding: CstIpiBindings()), 
		GetPage(name: Routes.cstIpiEditPage, page:()=> CstIpiEditPage()),
		GetPage(name: Routes.cstCofinsListPage, page:()=> const CstCofinsListPage(), binding: CstCofinsBindings()), 
		GetPage(name: Routes.cstCofinsEditPage, page:()=> CstCofinsEditPage()),
		GetPage(name: Routes.cstPisListPage, page:()=> const CstPisListPage(), binding: CstPisBindings()), 
		GetPage(name: Routes.cstPisEditPage, page:()=> CstPisEditPage()),
		GetPage(name: Routes.csosnListPage, page:()=> const CsosnListPage(), binding: CsosnBindings()), 
		GetPage(name: Routes.csosnEditPage, page:()=> CsosnEditPage()),
		GetPage(name: Routes.cnaeListPage, page:()=> const CnaeListPage(), binding: CnaeBindings()), 
		GetPage(name: Routes.cnaeEditPage, page:()=> CnaeEditPage()),
		GetPage(name: Routes.paisListPage, page:()=> const PaisListPage(), binding: PaisBindings()), 
		GetPage(name: Routes.paisEditPage, page:()=> PaisEditPage()),
		GetPage(name: Routes.nivelFormacaoListPage, page:()=> const NivelFormacaoListPage(), binding: NivelFormacaoBindings()), 
		GetPage(name: Routes.nivelFormacaoEditPage, page:()=> NivelFormacaoEditPage()),
		GetPage(name: Routes.tabelaPrecoListPage, page:()=> const TabelaPrecoListPage(), binding: TabelaPrecoBindings()), 
		GetPage(name: Routes.tabelaPrecoEditPage, page:()=> TabelaPrecoEditPage()),
		GetPage(name: Routes.tipoRelacionamentoListPage, page:()=> const TipoRelacionamentoListPage(), binding: TipoRelacionamentoBindings()), 
		GetPage(name: Routes.tipoRelacionamentoEditPage, page:()=> TipoRelacionamentoEditPage()),
		GetPage(name: Routes.sindicatoListPage, page:()=> const SindicatoListPage(), binding: SindicatoBindings()), 
		GetPage(name: Routes.sindicatoEditPage, page:()=> SindicatoEditPage()),
	];
}